namespace: zcubbs
name: general
version: 1.0.0
readme: README.md
authors:
- zcubbs <https://github.com/zcubbs>
description: General collection
license:
- MIT
license_file: ''
tags: []
dependencies: {}
repository: https://github.com/zcubbs/ansible-collection-general
documentation: https://github.com/zcubbs/ansible-collection-general
homepage: https://github.com/zcubbs/ansible-collection-general
issues: https://github.com/zcubbs/ansible-collection-general
build_ignore: []

