---
dependencies: []

galaxy_info:
  role_name: certbot
  author: zcubbs
  description: "Installs and configures Certbot (for Let's Encrypt)."
  company: "https://github.com/zcubbs"
  license: "MIT"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - networking
    - system
    - web
    - certbot
    - letsencrypt
    - encryption
    - certificates
    - ssl
    - https
