---

name: Release and Deploy collection
on: # yamllint disable-line rule:truthy
  workflow_dispatch:

env:
  working-directory: ./collection
  python-version: 3.8

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade ansible
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Copy files and directories to source
        run: |
          mkdir -p build/src
          cp $files build/src
          cp -rf $directories build/src
        env:
          files: "README.md galaxy.yml"
          directories: "roles meta"

      - name: Build Ansible Collection
        run: |
          ansible-galaxy collection build build/src --force

      - name: Get current version
        id: cversion
        run: |
          pip install yq
          echo "version=$(yq -r .version galaxy.yml)" >> $GITHUB_OUTPUT
          echo "$(yq -r .version galaxy.yml)"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: general-v${{ steps.cversion.outputs.version }}
          name: General v${{ steps.cversion.outputs.version }}
          body: |
            # Ansible Collection: zcubbs-general
            Install with:
            ```sh
            ansible-galaxy collection install -r requirements.yml -f
            ```
            The requirements.yml needs to have the following format and content:
            ```yaml
            ---
            collections:
                - https://github.com/zcubbs/ansible-collections/releases/download/v${{ steps.cversion.outputs.version }}/zcubbs-general-${{ steps.cversion.outputs.version }}.tar.gz
            ```
          draft: false
          prerelease: false
          files: |
            ${{github.workspace}}/collection/zcubbs-general-${{ steps.cversion.outputs.version }}.tar.gz

      - name: Duplicate Release
        id: duplicate_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: general-v${{ steps.cversion.outputs.version }}
          name: General v${{ steps.cversion.outputs.version }}
          repository: zcubbs/ansible-collections
          body: |
            # Ansible Collection: zcubbs-general
            Install with:
            ```sh
            ansible-galaxy collection install -r requirements.yml -f
            ```
            The requirements.yml needs to have the following format and content:
            ```yaml
            ---
            collections:
                - https://github.com/zcubbs/ansible-collections/releases/download/v${{ steps.cversion.outputs.version }}/zcubbs-general-${{ steps.cversion.outputs.version }}.tar.gz
            ```
          draft: false
          prerelease: false
          files: |
            ${{github.workspace}}/collection/zcubbs-general-${{ steps.cversion.outputs.version }}.tar.gz

      #- name: Deploy Ansible collection to Galaxy
      #  run: ansible-galaxy collection publish zcubbs-general-${{ steps.cversion.outputs.version }}.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}
